# GET http://localhost:3001/users

# POST http://localhost:3001/login


# { "email": "user@example.com"  ,
#     "password": "helloworld"
#  }
 http://localhost:3001/creatures?filter=sharks


GET http://localhost:3001/creatures


e.g 1001

int arrayBinary[];
    
int solution(int N){
     
   for(int i=0; i<arrayBinary.length()-1; i++){
       

   }

}